name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        # Ports to map
        ports:
          - 6379:6379
        # Set health checks to wait until redis is ready
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pandoc
        run: sudo apt-get install -y pandoc
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install .[test]
      - name: Test with pytest
        run: |
          export MISTRAL_API_KEY="${{ secrets.MISTRAL_API_KEY }}" && export HEYMANS_DEFAULT_MODEL="mistral-medium" && pytest tests/cheap
